Add infer static code analysis to CI
AntiMicroX/antimicrox pull request #290
Opened 2021-11-16 16:27 UTC by avinal

Fixes #289

## Proposed changes 

- Adds infer
- remove parallel from builds

----
Signed-off-by: Avinal Kumar <avinal.xlvii@gmail.com>

2021-11-16 22:21 UTC, pktiuk commented
Will reports from infer be also available in [security page](https://github.com/AntiMicroX/antimicrox/security/code-scanning)?

2021-11-17 05:57 UTC, avinal commented
> Will reports from infer be also available in [security page](https://github.com/AntiMicroX/antimicrox/security/code-scanning)?

No, security page requires reports in SARIF format, infer only emits JSON and text.

2021-11-17 09:00 UTC, pktiuk requested changes

2021-11-17 09:19 UTC, avinal commented on .github/workflows/static-code-analysis.yml
> +    infer-analysis:
ok I will add that too

2021-11-18 11:06 UTC, pktiuk commented on .github/workflows/static-code-analysis.yml
> +    infer-analysis:
Remember to resolve this conversation and Re-request review when you apply changes

2021-11-18 11:08 UTC, avinal commented on .github/workflows/static-code-analysis.yml
> +    infer-analysis:
Sure, I will complete it by the weekend.

2021-11-20 10:40 UTC, pktiuk approved these changes

2021-11-20 19:27 UTC, merged