Add QMutex
AntiMicroX/antimicrox pull request #351
Opened 2022-01-24 23:23 UTC by noisecode3

Protect generateLabel() and various SDL vars in gamecontroller class and axesStatus

I created QMutex object behind QMutexLocker that will get destroyed when method end in a clean way and easy to maintain.
These have been tested a lot by me and fixes all crashes when running the application but crashes can still happen if the user uses the Gui and changes something that is not stable in the application yet.

2022-01-25 00:09 UTC, pktiuk requested changes
Thank you for your contribution, but I have some questions.

I see that you are trying to protect some classes from changes happening in multiple threads at once.

But I don't understand one thing.

How this code:

```cpp
void FlashButtonWidget::refreshLabel()
{
    QMutex mutex;
    QMutexLocker locker(&mutex);
    QString temp = generateLabel();
    setText(temp);
    qDebug() << "label has been set: " << temp;
}
```

Is supposed to guard class `FlashButtonWidget` from refreshing label in multiple threads at once?   
Every thread calling this method would create a separate mutex creating a separate blockade, and due to this separation all of these threads won't lock each other.

2022-01-25 13:20 UTC, noisecode3 commented
For refreshLabel()
I think that lea assembly instruction is accessing a variable that is shared with another thread. Therefore a mutex like that should lock it. I have no proper education, Im not sure, can we put this on hold for some more time?

2022-01-25 14:26 UTC, pktiuk commented
> can we put this on hold for some more time?

Yes, it can wait.

2022-01-27 09:45 UTC, pktiuk commented
Linked with issue: #133

2022-01-28 11:41 UTC, noisecode3 commented
I think the compiler optimized to get value of a shared variable from cache one the cpu. I believe the compiler wont do this if threads was properly setup throughout the application. Therefore this cant be the right fix for this in the long term.

> Every thread calling this method would create a separate mutex creating a separate blockade, and due to this separation all of these threads won't lock each other.

I don't know what you're talking about here. It blocks it then it just gets rid if that object, its not supper expensive but not the best.

2022-01-28 11:41 UTC, closed without merging